### ISSUE TITLE
Feature: Failure notice and Malformed Input Highlighting

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI-appscript#2]
### Current State

While the triggers for the App Script do work, there is no external notification of a script failing to perform as expected. There is also no indication on the sheet which rows caused failure.

### TODO
- [x] Send an email on any unexpected exception for triggers
- [x] On early failure, highlight the cell with the issue and leave a comment with the reasoning
    - [x] Geocoding
    - [x] Mail quota reached
- [x] On a failure during the approval process, remove the approval
